{
  "$schema": "http://json.schemastore.org/sarif-2.1.0",
  "runs": [
    {
      "defaultSourceLanguage": "dockerfile",
      "properties": {
        "megalinter": {
          "docUrl": "https://megalinter.io/7.9.0/descriptors/dockerfile_hadolint",
          "linterKey": "DOCKERFILE_HADOLINT",
          "linterVersion": "2.12.0"
        }
      },
      "results": [],
      "tool": {
        "driver": {
          "downloadUri": "https://github.com/hadolint/hadolint",
          "fullName": "Haskell Dockerfile Linter",
          "informationUri": "https://megalinter.io/7.9.0/descriptors/dockerfile_hadolint",
          "name": "Hadolint (MegaLinter DOCKERFILE_HADOLINT)",
          "shortDescription": {
            "text": "Dockerfile linter, validate inline bash, written in Haskell"
          },
          "version": "2.12.0"
        }
      }
    }
  ],
  "version": "2.1.0"
}