---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  test_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # pin@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # pin@v2

      - name: Build
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # pin@v4
        with:
          push: false
