---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  test_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # pin@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # pin@v2

      - name: Build
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # pin@v4
        with:
          push: false
